version: "3.8"
services:
  dca-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dca-monitor
    restart: unless-stopped

   # IMPORTANT: placeholders so Portainer can substitute values
    environment:
      CHECK_YEAR: ${CHECK_YEAR}
      CHAT_WEBHOOK: ${CHAT_WEBHOOK}
      NTFY_URL: ${NTFY_URL}
      TZ: ${TZ:-Asia/Yangon}
      CRON_SCHEDULE: ${CRON_SCHEDULE:-0 9 * * *}
      CRON_BOOTSTRAP: ${CRON_BOOTSTRAP:-true}

    # If you add 'stack.env' to the repo, Portainer (Git mode) will read it.
    # Remove this if you prefer to ONLY use the Portainer Environment panel.
    env_file:
      - stack.env
    
    volumes:
      - dca-data:/data
    healthcheck:
      test: ["CMD", "sh", "-c", "pgrep crond >/dev/null && grep -q '.' /var/log/dca_monitor.log || true"]
      interval: 1m
      timeout: 5s
      retries: 3
volumes:
  dca-data:
